BaseUrl= "http://www.klassiekemuziek.live/"
LanguageCode= "nl"
Title= "Bosch en Duin klassieke muziek"
paginate = 5
#DisqusShortname = "YOUR_SHORT_NAME_HERE"
Copyright = "All rights reserved - 2018"
canonifyurls = true
theme = "casper2"


[params]
  description = "De Website van Bosch en Duin klassieke muziek. Hier bieden wij live klassieke concerten aan, met ondermeer piano en zang."
  metadescription = "De Website van Bosch en Duin klassieke muziek. Hier bieden wij live klassieke concerten aan, met ondermeer piano en zang."
  cover = "images/main.jpg"
  author = "Martin Kaptein"
  authorlocation = "Bosch en Duin, The Netherlands"
  authorwebsite = "https://www.martinkaptein.com"
  #authorbio= "my bio"
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-86096566-4"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  #RSSLink = "http://feeds.feedburner.com/..."
  #githubName = "vjeantet"
  #twitterName = "vjeantet"
  # facebookName = ""
  # codepenName = ""
  # linkedinName = ""
  # stackoverflowId = ""
  # keybaseName = ""
  # flickrName = ""
  # instagramName = ""
  # email = ""
  # pinterestName = ""
  # googlePlusName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  
  # Setting a value will load highlight.js and enable syntax highlighting using the style selected.
  # See https://github.com/isagalaev/highlight.js/tree/master/src/styles for available styles
  # A preview of above styles can be viewed at https://highlightjs.org/static/demo/
  hjsStyle = "default"

  [params.social]
   # twitter = "your_twitter"
   
   
[[menu.main]]
  name = "Archief"
  weight = -1
  identifier = "tags/archief"
  url = "/tags/archief"